### ISSUE TITLE
Create a way in backbone to send data from view to backend

### ISSUE THREAD

**Issue by drewrwilson** [drewrwilson/lestandsjs#44]
Need to have a way to save data from the "add an update" view to the backend. This is the relevant frontend route: `#/updates/add`.

So this will need to result in a POST json request that goes to some backend route. Which route will depend on the answer to #43

**Comment by techieshark** [comment]
I think this will be completed at the same time that #71 is; they're quite similar.

**Comment by techieshark** [comment]
I think #43 implemented the backend, and #71 implements the frontend of this, so I'm going to mark this as a duplicate and complete it. Feel free to open / comment if I'm confused about something.
