### ISSUE TITLE
form placeholder text hard to distinguish from real text

### ISSUE THREAD

**Issue by techieshark** [drewrwilson/lestandsjs#75]
On the add update form, it was hard to tell the placeholder text apart from actual entered text.

Perhaps we could make the former lighter and the latter darker?

Possibly useful: http://stackoverflow.com/questions/2610497/change-an-inputs-html5-placeholder-color-with-css

**Comment by drewrwilson** [comment]
@techieshark 

How's this look? 

![image](https://cloud.githubusercontent.com/assets/4324656/5639600/33acfa4e-95ce-11e4-8353-5ea17fddc6b7.png)

**Comment by techieshark** [comment]
:+1:
