### ISSUE TITLE
On the add-an-update page, the default date should be today's date

### ISSUE THREAD

**Issue by drewrwilson** [drewrwilson/lestandsjs#93]
![image](https://cloud.githubusercontent.com/assets/4324656/5659082/ccf01b1c-96c0-11e4-878d-8258036a6845.png)

**Comment by labham** [comment]
if you are using jquery datepicker, you can set the min date as today's date:

$( ".selector" ).datepicker( "setDate", new Date());

**Comment by drewrwilson** [comment]
thanks, @labham! In this project we're also using backbone, so dropping in some jquery is a little trickier than in situations with just HTML and jquery. The HTML for this page is in a template that we load into a backbone view, so we'll need to find where to place code like this so that loads when that HTML is in the DOM.

**Comment by labham** [comment]
I ahvent worked on backbone, but I have implemented the same thing in Angular. If you can share the specific js file and template, then I might be able to help.
